### ISSUE TITLE
Xcode9 Swift4 problem happened

### ISSUE THREAD

**Issue by limxing** [KevinZhouRafael/ActiveSQLite#1]
../Pods/ActiveSQLite/ActiveSQLite/Classes/DBModel+Query.swift:614:45: Call can throw, but it is not marked with 'try' and the error is not handled

.... fourteen problems

**Comment by KevinZhouRafael** [comment]
The DBModel+Query.swift:614:45 is bean commented.  Pleasse make sure you use 0.3.0 version.
