### ISSUE TITLE
type(of: self).isSaveDefaulttimestamp   Thread 1: EXC_BAD_ACCESS (code=1, address=0x41a10074cd6d)

### ISSUE THREAD

**Issue by wangkeshuai** [KevinZhouRafael/ActiveSQLite#7]
Hi，KevinZHouRafae
I use your framework like this 
  //获取Document目录
      let documentPath = NSSearchPathForDirectoriesInDomains(FileManager.SearchPathDirectory.documentDirectory, FileManager.SearchPathDomainMask.userDomainMask, true).last! + "/model.sqlite"
      print(documentPath)
      ASConfigration.setDefaultDB(path: documentPath, name: "model.sqlite")
      usrModel.name = "haha"
      try! usrModel.save()

/////////// DBModel is the base class of my model
import UIKit
import ActiveSQLite
import HandyJSON
class DBModel:ASModel,HandyJSON {
  required init(){}
}
but the project crashed when I was running

   internal func noSavedProperties() -> [String]{
        if type(of: self).isSaveDefaulttimestamp{ Thread 1: EXC_BAD_ACCESS (code=1, address=0x41a10074cd6d)
            return transientTypes()
        }else{
            return transientTypes() + [type(of: self).CREATE_AT_KEY,type(of: self).UPDATE_AT_KEY]
        }
    }

How should I solve this problem？ 

Thanks very much！

**Comment by longgeshashen** [comment]
I am also meet this Problem,if you solve it, please tell me. Thanks!

**Comment by KevinZhouRafael** [comment]
It's fixed in ActiveSQLite0.4.1 .
